// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrQyjAzAth-gm_4PM9amQ8HAtrCmryBI',
    appId: '1:861387070043:web:81037db6124bcb2ca1fd7e',
    messagingSenderId: '861387070043',
    projectId: 'cuaderno-profesor-d8800',
    authDomain: 'cuaderno-profesor-d8800.firebaseapp.com',
    storageBucket: 'cuaderno-profesor-d8800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwfar6W2HyCcWop3aHRoaJnUN4AXKhbo',
    appId: '1:861387070043:android:bfdefc1230c3bd49a1fd7e',
    messagingSenderId: '861387070043',
    projectId: 'cuaderno-profesor-d8800',
    storageBucket: 'cuaderno-profesor-d8800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGATO09-G7wcdMQDhZhJYhhBK0N8drR4',
    appId: '1:861387070043:ios:0132439afd06e642a1fd7e',
    messagingSenderId: '861387070043',
    projectId: 'cuaderno-profesor-d8800',
    storageBucket: 'cuaderno-profesor-d8800.firebasestorage.app',
    iosBundleId: 'com.example.cuadernoProfesor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey1234567890',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'cuaderno-profesor-demo',
    storageBucket: 'cuaderno-profesor-demo.appspot.com',
    iosBundleId: 'com.example.cuadernoProfesor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQrQyjAzAth-gm_4PM9amQ8HAtrCmryBI',
    appId: '1:861387070043:web:93560e7e6964f466a1fd7e',
    messagingSenderId: '861387070043',
    projectId: 'cuaderno-profesor-d8800',
    authDomain: 'cuaderno-profesor-d8800.firebaseapp.com',
    storageBucket: 'cuaderno-profesor-d8800.firebasestorage.app',
  );

}